services:
  frontend:
    build: ./frontend
    volumes:
      - frontend-build:/app/dist

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - database
    networks:
      - internal

  database:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=feedtrac
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - internal

  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - frontend-build:/usr/share/nginx/html
    networks:
      - internal

networks:
  internal: 
    driver: bridge

volumes:
  postgres-data:
  frontend-build: