services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:4000
      - VITE_APP_PORT=3000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/:/app/
      - frontend-node_modules:/app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    depends_on:
      - database
    volumes:
      - ./backend/src:/app/src

  database:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=feedtrac
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  frontend-node_modules: