services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=feedtrac
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - feedtrac-network

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/feedtrac?schema=public
      - PORT=4000
    volumes:
      - ./src:/src
    networks:
      - feedtrac-network

  frontend:
    build: ./frontend  
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - feedtrac-network

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   networks:
  #     - feedtrac-network

networks:
  feedtrac-network: 
    driver: bridge

volumes:
  postgres-data: