FROM oven/bun:1
WORKDIR /app
COPY package.json bun.lock prisma/schema.prisma .env.production ./
RUN bun install --frozen-lockfile
RUN bun run prisma:deploy-prod
COPY . .
EXPOSE 4000
CMD ["bun", "run", "start"]